#!/bin/bash

set -e

VERSION=$1

if test -z "$VERSION";then
	echo "Use as make-release VERSION"
	exit 1
fi

PACKAGE=gnutls
# Initial variables which help the scripts share
RELEASE_SPEC=$PWD/$PACKAGE.spec
RELEASE_SRPM_DIR=$PWD/_release/srpm
RELEASE_SOURCE=$PWD/_release/source
RELEASE_DEBIAN_REPO=$PWD/_release/debian-apt
TOOLS_DIR=$PWD
SCRIPTS_DIR=/home/nmavrogi/cvs/cockpituous-mine/release

#rm -rf $RELEASE_SOURCE
mkdir -p $RELEASE_SOURCE

pushd $RELEASE_SOURCE

if ! test -f "$PACKAGE-$VERSION.tar.xz";then
	wget ftp://ftp.gnutls.org/gcrypt/gnutls/v3.5/$PACKAGE-$VERSION.tar.xz
fi

if ! test -f "$PACKAGE-$VERSION.tar.xz.sig";then
	wget ftp://ftp.gnutls.org/gcrypt/gnutls/v3.5/$PACKAGE-$VERSION.tar.xz.sig
fi

gpg --verify $PACKAGE-$VERSION.tar.xz.sig

cp $TOOLS_DIR/patches/*.patch .

if ! test -f $PACKAGE-$VERSION-hobbled.tar.xz;then
	test -d "$PACKAGE-$VERSION" && rm -rf "$PACKAGE-$VERSION"
	tar xf $PACKAGE-$VERSION.tar.xz
	pushd "$PACKAGE-$VERSION"
	$TOOLS_DIR/hobble-gnutls -e
	popd

	rm -f "$PACKAGE-$VERSION-hobbled.tar" "$PACKAGE-$VERSION-hobbled.tar.xz" || true
	tar cf $PACKAGE-$VERSION-hobbled.tar "$PACKAGE-$VERSION"
	xz $PACKAGE-$VERSION-hobbled.tar
fi

popd

# Build the source tarball patches and srpm

rm -rf $RELEASE_SRPM_DIR
mkdir -p $RELEASE_SRPM_DIR
pushd $RELEASE_SRPM_DIR
export RELEASE_SOURCE
export RELEASE_TAG="$VERSION"
export RELEASE_SPEC
export RELEASE_PATCH=1
export RELEASE_TARBALL="$RELEASE_SOURCE/$PACKAGE-$VERSION-hobbled.tar.xz"
$SCRIPTS_DIR/release-srpm -p
popd

RELEASE_SRPM=$(ls $RELEASE_SRPM_DIR/$PACKAGE-*.src.rpm)

# Do fedora builds for the tag, using tarball
$SCRIPTS_DIR/release-koji -v -p $RELEASE_SRPM master
$SCRIPTS_DIR/release-koji -v -p $RELEASE_SRPM f25

export RELEASE_SRPM
$SCRIPTS_DIR/release-bodhi f25

